name: Build and Release

on:
  push:
    tags:
      - 'v*'  # 当推送以 v 开头的标签时触发
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'yarn'
        
    - name: Install dependencies
      run: yarn install --frozen-lockfile
      
    - name: Build web assets
      run: yarn build:web

    - name: 查看dist文件列表
      run: ls ./dist/web

    - name: Build Electron app
      run: yarn build:electron
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: 查看dist文件列表
      run: ls ./dist/electron
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: electron-app-${{ matrix.os }}
        path: dist/electron/
        retention-days: 30

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        body: |
          ## 更新内容
          
          - 自动构建的 Electron 应用
          - 支持 macOS、Windows、Linux 平台
          
          ## 下载说明
          
          请根据您的操作系统下载对应的安装包：
          - macOS: `.dmg` 文件
          - Windows: `.exe` 文件  
          - Linux: `.AppImage` 文件
        files: |
          artifacts/electron-app-macos-latest/**/*
          artifacts/electron-app-windows-latest/**/*
          artifacts/electron-app-ubuntu-latest/**/*
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}