name: Build and Release

on:
  push:
    tags:
      - 'v*'  # 当推送以 v 开头的标签时触发
  workflow_dispatch:  # 允许手动触发

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'yarn'
        
    - name: Install dependencies
      run: yarn install --frozen-lockfile
      
    - name: Build web assets
      run: yarn build:web

    # - name: 查看dist文件列表
    #   run: |
    #     if [[ "$RUNNER_OS" == "Windows" ]]; then
    #       dir ./dist/web
    #     else
    #       ls -la ./dist/web
    #     fi

    - name: Build Electron app
      run: yarn build:electron

    # - name: 查看构建产物
    #   run: |
    #     if [[ "$RUNNER_OS" == "Windows" ]]; then
    #       dir ./dist/electron/
    #     else
    #       ls -la ./dist/electron/
    #     fi
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: electron-app-${{ matrix.os }}
        path: dist/electron/
        retention-days: 30

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts

    - name: List artifacts for debugging
      run: |
        echo "=== Artifacts structure ==="
        find artifacts -type f -name "*.dmg" -o -name "*.exe" -o -name "*.zip" | head -10
        echo "=== All files ==="
        find artifacts -type f | head -20
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        body: |
          ## 更新内容
          
          - 自动构建的 Electron 应用
          - 支持 macOS、Windows 平台
          
          ## 下载说明
          
          请根据您的操作系统下载对应的安装包：
          - macOS: `.dmg` 文件
          - Windows: `.exe` 文件
        files: |
          artifacts/electron-app-macos-latest/*.dmg
          artifacts/electron-app-macos-latest/*.zip
          artifacts/electron-app-windows-latest/*.exe
          artifacts/electron-app-windows-latest/*.zip
        draft: false
        prerelease: false
        overwrite: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}