
name: release

on:
  push:
    tags:
      - 'v*'

jobs:
    release:
        runs-on: macos-10.15
        steps:
            - name: 拉仓库
              uses: actions/checkout@v2
              with:
                fetch-depth: 1
            - uses: actions/setup-node@v1
              with:
                node-version: '22'
                check-latest: true
            # - name: 调整shell脚本权限
            #   run: chmod 777 ./get_package.sh
            # - name: 执行shell脚本，获取package.json对象
            #   id: pkg
            #   run: ./get_package.sh
            # - name: 查看版本号
            #   run: echo ${{ steps.pkg.outputs.version }}
            - name: 安装依赖
              run: yarn install
            # - name: 打包web
            #   run: npm run build:web
            - name: 打包electron
              run: npm run electron:build
            - name: 查看dist文件列表
              run: ls ./dist/electron
            - name: 创建release
              id: create_release
              uses: actions/create-release@v1
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                tag_name: ${{ github.ref }}
                release_name: ${{ github.ref }}
                draft: false
                prerelease: false
            - name: 上传Release静态资源 latest-mac.yml
              uses: actions/upload-release-asset@v1
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                upload_url: ${{ steps.create_release.outputs.upload_url }}
                asset_path: ./dist/electron/latest-mac.yml
                asset_name: latest-mac.yml
                asset_content_type: text/plain
            - name: 上传Release静态资源 latest.yml
              uses: actions/upload-release-asset@v1
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                upload_url: ${{ steps.create_release.outputs.upload_url }}
                asset_path: ./dist/electron/latest.yml
                asset_name: latest.yml
                asset_content_type: text/plain
            - name: 上传Release静态资源 exe
              uses: actions/upload-release-asset@v1
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                upload_url: ${{ steps.create_release.outputs.upload_url }}
                asset_path: ./dist/electron/${{ steps.pkg.outputs.productName }}-${{ steps.pkg.outputs.version }}.exe
                asset_name: ${{ steps.pkg.outputs.productName }}-${{ steps.pkg.outputs.version }}.exe
                asset_content_type: application/octet-stream
            - name: 上传Release静态资源 exe.blockmap
              uses: actions/upload-release-asset@v1
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                upload_url: ${{ steps.create_release.outputs.upload_url }}
                asset_path: ./dist/electron/${{ steps.pkg.outputs.productName }}-${{ steps.pkg.outputs.version }}.exe.blockmap
                asset_name: ${{ steps.pkg.outputs.productName }}-${{ steps.pkg.outputs.version }}.exe.blockmap
                asset_content_type: application/x-gzip
            - name: 上传Release静态资源 dmg
              uses: actions/upload-release-asset@v1
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                upload_url: ${{ steps.create_release.outputs.upload_url }}
                asset_path: ./dist/electron/${{ steps.pkg.outputs.productName }}-${{ steps.pkg.outputs.version }}.dmg
                asset_name: ${{ steps.pkg.outputs.productName }}-${{ steps.pkg.outputs.version }}.dmg
                asset_content_type: application/octet-stream
            - name: 上传Release静态资源 mac.zip
              uses: actions/upload-release-asset@v1
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                upload_url: ${{ steps.create_release.outputs.upload_url }}
                asset_path: ./dist/electron/${{ steps.pkg.outputs.productName }}-${{ steps.pkg.outputs.version }}-mac.zip
                asset_name: ${{ steps.pkg.outputs.productName }}-${{ steps.pkg.outputs.version }}-mac.zip
                asset_content_type: application/octet-stream
            - name: 上传Release静态资源 dmg.blockmap
              uses: actions/upload-release-asset@v1
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                upload_url: ${{ steps.create_release.outputs.upload_url }}
                asset_path: ./dist/electron/${{ steps.pkg.outputs.productName }}-${{ steps.pkg.outputs.version }}.dmg.blockmap
                asset_name: ${{ steps.pkg.outputs.productName }}-${{ steps.pkg.outputs.version }}.dmg.blockmap
                asset_content_type: application/x-gzip
